services:
    #---------------------Hide Applicatin sonata user bundle
    sonata.user.admin.user:
        class: %sonata.user.admin.user.class%
        arguments: [~, %sonata.user.admin.user.entity%, %sonata.user.admin.user.controller%]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        calls:
            - [setTranslationDomain,['AppBundle']]
            - [setUserManager,['@fos_user.user_manager']]
    sonata.user.admin.group:
        abstract: true
        public: false
    #--------------------User
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, AppBundle:UserAdmin]
        calls:
            - [setTranslationDomain,['AppBundle']]
            - [setUserManager,['@fos_user.user_manager']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Carnet",label: "Contacts", label_translator_strategy: "sonata.admin.label.strategy.underscore", icon: '<i class="fa fa-book"></i>', show_in_dashboard: true }

    app.admin.group:
        class: AppBundle\Admin\GroupAdmin
        arguments: [~, AppBundle\Entity\Group, AppBundle:GroupAdmin]
        calls:
            - [setTranslationDomain,['AppBundle']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Groups", label_translator_strategy: "sonata.admin.label.strategy.underscore", icon: "%sonata.user.admin.groupicon%", show_in_dashboard: false }